repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0  # важно зафиксировать версию с поддержкой toml
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
        exclude: ^migrations/
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest ./mis/tests.py
        language: system
        pass_filenames: false
        always_run: true
