# Generated by Django 5.2.3 on 2025-06-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultations",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-06-15 11:54:00.000 +0400", verbose_name="Дата создания"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consultations",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="mis.clinics",
                verbose_name="Клиника",
            ),
        ),
        migrations.AlterField(
            model_name="consultations",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="mis.doctors",
                verbose_name="Врач",
            ),
        ),
        migrations.AlterField(
            model_name="consultations",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="mis.patients",
                verbose_name="Пациент",
            ),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="specialization",
            field=models.CharField(max_length=100, verbose_name="Специальность"),
        ),
        migrations.AlterField(
            model_name="patients",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="users",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("admin", "Администратор"), ("doctor", "Врач"), ("patient", "Пациент")],
                default="patient",
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="Логин (не обязательно)"
            ),
        ),
    ]
